language: node_js
node_js:
  - "13"

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm test
